// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package developer_profile

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type DeveloperProfile struct {
	ID                   uuid.UUID
	Name                 string
	Email                string
	Phone                sql.NullString
	Address              sql.NullString
	AcceptTermsOfService bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
