// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package developer_profile

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeveloperProfile = `-- name: CreateDeveloperProfile :one
INSERT INTO developer_profiles (name, email, phone, address, accept_terms_of_service)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, address, accept_terms_of_service, created_at, updated_at
`

type CreateDeveloperProfileParams struct {
	Name                 string
	Email                string
	Phone                sql.NullString
	Address              sql.NullString
	AcceptTermsOfService bool
}

func (q *Queries) CreateDeveloperProfile(ctx context.Context, arg CreateDeveloperProfileParams) (DeveloperProfile, error) {
	row := q.db.QueryRowContext(ctx, createDeveloperProfile,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.AcceptTermsOfService,
	)
	var i DeveloperProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.AcceptTermsOfService,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeveloperProfile = `-- name: DeleteDeveloperProfile :exec
DELETE FROM developer_profiles
WHERE id = $1
`

func (q *Queries) DeleteDeveloperProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeveloperProfile, id)
	return err
}

const getDeveloperProfile = `-- name: GetDeveloperProfile :one
SELECT id, name, email, phone, address, accept_terms_of_service, created_at, updated_at
FROM developer_profiles
WHERE id = $1
`

func (q *Queries) GetDeveloperProfile(ctx context.Context, id uuid.UUID) (DeveloperProfile, error) {
	row := q.db.QueryRowContext(ctx, getDeveloperProfile, id)
	var i DeveloperProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.AcceptTermsOfService,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeveloperProfiles = `-- name: ListDeveloperProfiles :many
SELECT id, name, email, phone, address, accept_terms_of_service, created_at, updated_at
FROM developer_profiles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDeveloperProfilesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDeveloperProfiles(ctx context.Context, arg ListDeveloperProfilesParams) ([]DeveloperProfile, error) {
	rows, err := q.db.QueryContext(ctx, listDeveloperProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeveloperProfile
	for rows.Next() {
		var i DeveloperProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.AcceptTermsOfService,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeveloperProfile = `-- name: UpdateDeveloperProfile :one
UPDATE developer_profiles
SET name                    = $2,
    email                   = $3,
    phone                   = $4,
    address                 = $5,
    accept_terms_of_service = $6,
    updated_at              = NOW()
WHERE id = $1
RETURNING id, name, email, phone, address, accept_terms_of_service, created_at, updated_at
`

type UpdateDeveloperProfileParams struct {
	ID                   uuid.UUID
	Name                 string
	Email                string
	Phone                sql.NullString
	Address              sql.NullString
	AcceptTermsOfService bool
}

func (q *Queries) UpdateDeveloperProfile(ctx context.Context, arg UpdateDeveloperProfileParams) (DeveloperProfile, error) {
	row := q.db.QueryRowContext(ctx, updateDeveloperProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.AcceptTermsOfService,
	)
	var i DeveloperProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.AcceptTermsOfService,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
